# Generated by Django 2.2.4 on 2019-08-13 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zip_app', '0002_comment_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='response',
            field=models.CharField(blank=True, max_length=900),
        ),
    ]
